### ISSUE TITLE
How does this compare with devenv.sh?

### ISSUE THREAD

**Issue by inscapist** [inscapist/ruby-nix#32]
Just found out about devenv and it seems rather popular but I have not tried it. 

For those who have tried it, is it on par with `ruby-nix` in terms of functionality?
If so, maybe we can sunset this project..

**Comment by emptyflask** [comment]
I've looked at it before but never tried it out. Interesting that it doesn't seem to use bundix at all, at least, there's no mention of it in the repo.

**Comment by emptyflask** [comment]
Ok so I've spent  several hours with it, and despite being impressive so far, it still has some rough edges, like crashing when requiring packages like `curl`. The python-rewrite branch is supposed to fix some of these issues, but I wasn't able to get it fully working.

devenv.sh is going to be nice once it's more mature, until then I'm sticking with ruby-nix!

**Comment by emptyflask** [comment]
https://www.jetpack.io/devbox is another one to check out...

**Comment by inscapist** [comment]
thanks for the info! devenv and devbox seem to make the entry to Nix way lower now
