### ISSUE TITLE
Gemfile `ruby: file` unsupported

### ISSUE THREAD

**Issue by J-Swift** [inscapist/ruby-nix#44]
Maybe I'm not configuring something properly on my end, but it looks like providing ruby version in a Gemfile doesnt work.

e.g. if I do this in my Gemfile
```
ruby file: '.ruby-version'
```

if fails with

```
/nix/store/3h12slpvxj5gxmwv9xgpc8c85lqb4lba-ruby-3.2.2/lib/ruby/3.2.0/bundler/definition.rb:442:in `validate_ruby!': Your Ruby version is 3.2.2, but your Gemfile specified  (Bundler::RubyVersionMismatch)
```

but if I do it explicitly

```
ruby '3.2.2'
```

it works. I assume its because the version file isnt being copied to the store, but it also seems like it should still work at runtime since the version file exists? I added ruby-nix to an existing project that was working before, so its definitely configured properly at a basic level.

EDIT: it also turns out that this old-style of specifying the path also works

```
ruby File.read('.ruby-version').strip
```

**Comment by inscapist** [comment]
I wasn't able to replicate this. But in any case, you should use the `ruby File.read('.ruby-version')` syntax

**Comment by J-Swift** [comment]
Hmm the only other thing I can think of is that Im specifying the ruby version explicitly for nix (ruby = pkgs.ruby_3_2) instead of reading the file. That could be why its not in the store. Wont be back into the office until monday to check.

**Comment by inscapist** [comment]
If it's not too much trouble, could you make a small reproducible example? Or maybe share the flake.nix here?

**Comment by J-Swift** [comment]
@inscapist will do. Hopefully sometime next week

**Comment by J-Swift** [comment]
@inscapist heres a basic repro off a `rails new`: https://github.com/J-Swift/rubynix-repro

**Comment by inscapist** [comment]
thank you. I will take a look tomorrow

**Comment by inscapist** [comment]
@J-Swift the issue actually stems from the version of bundler being used. In the repro, your bundler version is 2.4.10 but the new syntax is only supported in 2.4.19 and above

https://github.com/rubygems/rubygems/releases/tag/bundler-v2.4.19

**Comment by inscapist** [comment]
This syntax is probably the new default for newer versions of rails. I am sure more people will be affected by this. 

So thanks for the report!

**Comment by J-Swift** [comment]
Hmm weird. Good catch. Previously I was running via docker and other team
members are running bare metal (no nix) so Ill have to figure out what
bundler was being used before.

**Comment by J-Swift** [comment]
Also, thanks for this project. It greatly simplified moving to nix on rails. Id tried a few times before and never could get it working quite right so Ive been sticking to docker for rails. Now I get nix + bare metal performance… win+win!

**Comment by inscapist** [comment]
I know what you mean, that's great to hear!
