### ISSUE TITLE
What to do with binstubs?

### ISSUE THREAD

**Issue by nyghtly-derek** [inscapist/ruby-nix#51]
I recently switched over an application to use ruby-nix. However, I ran into a few errors with the wrong versions of bundler and other gems being used when I ran `rake`, `rubocop`, and others. I thought this might have to with some legacy binstubs that I have from an older version of the application that managed gems differently. I removed those and it seems to have fixed the problem.

My question: Should I use bundler to generate new binstubs after switching over to ruby-nix? Or should I not have any binstubs at all? I sort of assumed it's the latter, but I want to make sure. 

Thanks again for this excellent tool! Our workflow to upgrade gems has improved dramatically after making the switch. We went from 55 minutes down to 30 seconds!

**Comment by inscapist** [comment]
>  We went from 55 minutes down to 30 seconds!

that's great!

> My question: Should I use bundler to generate new binstubs after switching over to ruby-nix? Or should I not have any binstubs at all? I sort of assumed it's the latter, but I want to make sure.

You most likely don't want or need binstubs. We had some legacy binstubs in our project that we didn't bother to clean up, but we never use them. 

You don't need `bundle exec xxx` either, but it shouldn't cause any harm to do so

**Comment by nyghtly-derek** [comment]
Thanks for the advice! That's helpful.

**Comment by nyghtly-derek** [comment]
In the end, I decided to remove all of my old binstubs, but re-generate a few that are specific to spring:
```
➜ spring binstub --all
* bin/rake: upgraded
* bin/rspec: upgraded
* bin/rails: upgraded
```

**Comment by emptyflask** [comment]
Especially if you're working with others who might not be using nix, double check your binstubs and make sure they don't contain /nix/store paths.
